using System;
using System.Reflection;
using System.Runtime.InteropServices;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: ComVisibleAttribute(false)]
[assembly: AssemblyTitleAttribute("flickrDownloadr")]
[assembly: AssemblyDescriptionAttribute("A desktop application for windows that would help download all (or selected) phot" +
    "os from the user\'s photostream (in one of the selected sizes) along with the tag" +
    "s, titles and descriptions.")]
[assembly: AssemblyConfigurationAttribute("Release")]
[assembly: AssemblyCompanyAttribute("http://flickrdownloadr.com")]
[assembly: AssemblyProductAttribute("flickr downloadr")]
[assembly: AssemblyCopyrightAttribute("Copyright © 2012-2013 Haridas Pachuveetil")]
[assembly: AssemblyTrademarkAttribute("")]
[assembly: AssemblyCultureAttribute("")]
[assembly: AssemblyVersionAttribute("0.7.0.3")]
[assembly: AssemblyFileVersionAttribute("0.7.0.3")]
[assembly: AssemblyInformationalVersionAttribute("0.7")]

