using System.Reflection;
using System.Runtime.InteropServices;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: ComVisible(false)]
[assembly: AssemblyTitle("flickrDownloadr")]
[assembly: AssemblyDescription("A desktop application for windows that would help download all (or selected) phot" +
                               "os from the user\'s photostream (in one of the selected sizes) along with the tag" +
                               "s, titles and descriptions.")]
[assembly: AssemblyConfiguration("Release")]
[assembly: AssemblyCompany("http://flickrdownloadr.com")]
[assembly: AssemblyProduct("flickr downloadr")]
[assembly: AssemblyCopyright("Copyright © 2012-2013 Haridas Pachuveetil")]
[assembly: AssemblyTrademark("")]
[assembly: AssemblyCulture("")]
[assembly: AssemblyVersion("0.6.5.1")]
[assembly: AssemblyFileVersion("0.6.5.1")]
[assembly: AssemblyInformationalVersion("0.6")]